name: WakaTime Stats

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 00:00 UTC 自动运行
  workflow_dispatch:      # 允许手动触发

jobs:
  update-readme:
    name: 更新 WakaTime 统计
    runs-on: ubuntu-latest

    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LANGUAGE: "true"
          SHOW_PROJECTS: "true"
          SHOW_OS: "true"
          SHOW_EDITORS: "true"
          SHOW_TIMEZONE: "true"
          SHOW_COMMIT: "true"
          SHOW_LINES_OF_CODE: "true"
          SHOW_PROFILE_VIEWS: "true"
          SHOW_UPDATED_DATE: "true"
